export const FETCH_RANDOM_JOKE_REQUEST = 'FETCH_RANDOM_JOKE_REQUEST';
export const FETCH_RANDOM_JOKE_SUCCESS = 'FETCH_RANDOM_JOKE_SUCCESS';
export const FETCH_RANDOM_JOKE_FAILURE = 'FETCH_RANDOM_JOKE_FAILURE';
